#define MRP_HISTORY_EVT_MAX

typedef struct tagMrpFsmAppl{
    UCHAR ucCurState;
    UCHAR ucHistoryNextIndex;
    UCHAR ucIsHistoryArrayFull;
    UCHAR ucRsvd;
    UINT16 ausHistoryStateEvt[MRP_HISTORY_EVT_MAX];
}MRP_FSM_APPL_S;

typedef struct tagMrpFsmReg{
    UINT32 uiLeaveTimeCountDown;
    UCHAR ucCurState;
    UCHAR ucHistoryNextIndex;
    UCHAR ucIsHistoryArrayFull;
    UCHAR ucRsvd;
    UINT16 ausHistoryStateEvt[MRP_HISTORY_EVT_MAX];
}MRP_FSM_REG_S;

typedef struct tagMrpFsmPrd {
    UINT32 uiPeriodicTimeCountDown;
    UCHAR ucCurState;
    UCHAR ucHistoryNextIndex;
    UCHAR ucIsHistoryArrayFull;
    UCHAR ucRsvd;
    UINT16 ausHistoryStateEvt[MRP_HISTORY_EVT_MAX];
}MRP_FSM_PRD_S;

typedef struct tagMrpFsmLA{
    UINT32 uiLATimeCountDown;
    UCHAR ucCurState;
    UCHAR ucHistoryNextIndex;
    UCHAR ucIsHistoryArrayFull;
    UCHAR ucRsvd;
    UINT16 ausHistoryStateEvt[MRP_HISTORY_EVT_MAX];
}MRP_FSM_LA_S;

typedef struct tagMrpFsmTable{
    UCHAR usNextState;
    UCHAR aucAction[2];
}MRP_FSM_TBL_S;

typedef enum enumMrpEvt{
    MRP_EVT_BEGIN,
    MRP_EVT_NEW,,
    MRP_EVT_JOIN,
    MRP_EVT_LV,

    MRP_EVT_TX,
    MRP_EVT_TXLA,
    MRP_EVT_TXLAF,

    MRP_EVT_RENEW,
    MRP_EVT_RJOININ,
    MRP_EVT_RIN,
    MRP_EVT_RJOINMT,
    MRP_EVT_RLV,
    MRP_EVT_RLA,

    MRP_EVT_FLUSH,
    MRP_EVT_REDECLARE,

    MRP_EVT_PERIODIC,
    MRP_EVT_PERIODICENALE,
    MRP_EVT_PERIODICDSIABLE,

    MRP_EVT_LEAVETIMER,
    MRP_EVT_LEAVEALLLTIMER,
    MRP_EVT_PERIODICTIMER,

    MRP_EVT_TX_FOR_LA_ONLY,
    MRP_EVT_MAX
}MRP_EVT_E;

typedef enum enumMrpFsmType{
    MRP_FSM_APPL,
    MRP_FSM_REG,
    MRP_FSM_LA,
    MRP_FSM_PRD,
    MRP_FSM_MAX
}MRP_FSM_TYPE_E;

UCHAR g_aucMrpEvtToFsmEvt[MRP_EVT_MAX][MRP_FSM_MAX] =
{
    // MRP_EVT_BEGIN
    {MRP_EVT_APPL_BEGIN, MRP_EVT_REG_BEGIN, MRP_EVT_LA_BEGIN, MRP_EVT_PRD_BEGIN},
    // MRP_EVT_NEW
    {MRP_EVT_APPL_NEW, MRP_EVT_REG_MAX,MRP_EVT_LA_MAX,MRP_EVT_PRD_MAX},
    // MRP_EVT_JOIN
    {MRP_EVT_APPL_JOIN, MRP_EVT_REG_MAX, MRP_EVT_LA_MAX, MRP_EVT_PRD_MAX},
    // MRP_EVT_LV
    {MRP_EVT_APPL_LV, MRP_EVT_REG_MAX, MRP_EVT_LA_MAX, MRP_EVT_PRD_MAX},
    // MRP_EVT_TX
    {MRP_EVT_APPL_TX, MRP_EVT_REG_MAX, MRP_EVT_LA_TX, MRP-MRP_EVT_PRD_MAX}，
    // MRP_EVT_TXLA
    {MRP_EVT_APPL_TXLA, MRP_EVT_REG_TXLA, MRP_EVT_LA_TX, MRP_EVT_PRD_MAX},
    // MRP_EVT_TXLAF,
    {MRP_EVT_APPL_TXLAF, MRP_EVT_REG_MAX, MRP_EVT_LA_MAX, MRP_EVT_PRD_MAX},
    // MRP_EVT_RNEW
    {MRP_EVT_APPL_RNEW, MRP_EVT_REG_RNEW, MRP_EVT_LA_MAX, MRP_EVT_PRD_MAX},
    // MRP_EVT_RJOININ
    {MRP_EVT_APPL_RJOININ, MRP_EVT_REG_RJOININ, MRP_EVT_LA_MAX, MRP_EVT_PRD_MAX},
    // RIN 
    {MRP_EVT_APPL_RIN, MRP_EVT_REG_MAX, MRP_EVT_LA_MAX, MRP_EVT_PRD_MAX},
    //RJOINMT 
    {MRP_EVT_APPL_RJOINMT, MRP_EVT_REG_RJOINMT, MRP_EVT_LA_MAX, MRP_EVT_PRD_MAX},
    //RMT
    {MRP_EVT_APPL_RMT, MRP_EVT_REG_MAX, MRP_EVT_LA_MAX, MRP_EVT_PRD_MAX},
    //RLV 
    {MRP_EVT_APPL_RLV, MRP_EVT_REG_RLV, MRP_EVT_LA_MAX, MRP_EVT_PRD_MAX},
    //RLA 
    {MRP_EVT_APPL_RLA, MRP_EVT_REG_RLA, MRP_EVT_LA_RLA, MRP-MRP_EVT_PRD_MAX},
    //FLUSH 
    {MRP_EVT_APPL_MAX, MRP_EVT_REG_FLUSH, MRP_EVT_LA_MAX, MRP_EVT_PRD_MAX},
    //REDECLARE 
    {MRP_EVT_APPL_REDECLARE, MRP_EVT_REG_REDECLARE, MRP_EVT_LA_MAX, MRP_EVT_PRD_MAX},
    //PERIODIC 
    {MRP_EVT_APPL_PERIODIC, MRP_EVT_REG_PERIODIC,MRP_EVT_LA_MAX, MRP_EVT_PRD_MAX},
    // MRP_EVT_PERIODICENALE
    {MRP_EVT_APPL_PERIODICENALE, MRP_EVT_REG_PERIODICENALE, MRP_EVT_LA_MAX, MRP_EVT_PRD_PERIODICENABLE},
    // MRP_EVT_PERIODICDSIABLE
    {MRP_EVT_APPL_PERIODICDISABLE, MRP_EVT_REG_PERIODICDISABLE, MRP_EVT_LA_MAX, MRP_EVT_PRD_PERIODICDISABLE},
    // MRP_EVT_LEAVETIMER
    {MRP_EVT_APPL_MAX, MRP_EVT_REG_LEAVETIMER, MRP_EVT_LA_MAX, MRP_EVT_PRD_MAX},
    // MRP_EVT_LEAVEALLTIMER
    {MRP_EVT_APPL_MAX, MRP_EVT_REG_MAX, MRP_EVT_LA_MAX, MRP_EVT_PRD_MAX},
    // MRP_EVT_PERIODICTIMER
    {MRP_EVT_APPL_MAX, MRP_EVT_REG_MAX, MRP_EVT_LA_MAX, MRP_EVT_PRD_PERIODICTIMER},
    // MRP_EVT_TX_FOR_LA_ONLY
    {MRP_EVT_APPL_MAX, MRP_EVT_REG_MAX, MRP_EVT_LA_TX, MRP_EVT_PRD_MAX},
    // MRP_EVT_MAX
    {MRP_EVT_APPL_MAX, MRP_EVT_REG_MAX, MRP_EVT_LA_MAX, MRP_EVT_PRD_MAX},
};













