typedef enum enumMrpStatePrd
{
	MRP_STATE_PRD_ACTIVE,
	MRP_STATE_PRD_PASSIVE,
	MRP_STATE_PRD_MAX
}MRP_STATE_PRD_E;

typedef enum enumMrpEvtPrd
{
	MRP_EVT_PRD_BEGIN,
	MRP_EVT_PRD_PERIODICENABLE,
	MRP_EVT_PRD_PERIODICDISABLE,
	MRP_EVT_PRD_PERIODICTIMER,
	MRP_EVT_PRD_MAX
}MRP_EVT_PRD_E;

typedef enum enumMrpPAPrd
{
	MRP_PA_PRD_STARTPERIODICTIMER,
	MRP_PA_PRD_PERIODIC,
	MRP_PA_PRD_MAX
}MRP_PA_PRD_E;