UCHAR *g_apucFsmLAStateName[MRP_STATE_LA_MAX+1]=
{
	"Passive", 
	"Active",
	"ERROR"
};

UCHAR *g_apucFsmLAEvtName[MRP_EVT_LA_MAX+1]
{
	"Begin!",
	"tx",
	"rLA",
	"leavealltimer!",
	"ERROR"
};

MRP_FSM_TBL_S g_astMrpFsmTblLeaveAll[MRP_EVT_LA_MAX][MRP_STATE_LA_MAX]=
{
	/*MRP_EVT_LA_BEGIN*/
	{
		/*MRP_STATE_LA_ACTIVE*/
		{MRP_STATE_LA_PASSIVE,{MRP_PA_LA_STARTLEAVEALLTIMER,MRP_PA_LA_MAX}},
		/*MRP_STATE_LA_PASSIVE*/
		{MRP_STATE_LA_PASSIVE,{MRP_PA_LA_STARTLEAVEALLTIMER,MRP_PA_LA_MAX}},
		
	},
	/*MRP_EVT_LA_TX*/
	{
		/*MRP_STATE_LA_ACTIVE*/
		{MRP_STATE_LA_PASSIVE,{MRP_PA_LA_SLA,MRP_PA_LA_MAX}},
		/*MRP_STATE_LA_PASSIVE*/
		{MRP_STATE_LA_MAX,{MRP_PA_LA_STARTLEAVEALLTIMER,MRP_PA_LA_MAX}},
		
	},
	/*MRP_EVT_LA_RLA*/
	{
		/*MRP_STATE_LA_ACTIVE*/
		{MRP_STATE_LA_PASSIVE,{MRP_PA_LA_STARTLEAVEALLTIMER,MRP_PA_LA_MAX}},
		/*MRP_STATE_LA_PASSIVE*/
		{MRP_STATE_LA_PASSIVE,{MRP_PA_LA_STARTLEAVEALLTIMER,MRP_PA_LA_MAX}},
		
	},
	/*MRP_EVT_LA_LEAVEALLTIMER*/
	{
		/*MRP_STATE_LA_ACTIVE*/
		{MRP_STATE_LA_ACTIVE,{MRP_PA_LA_STARTLEAVEALLTIMER,MRP_PA_LA_MAX}},
		/*MRP_STATE_LA_PASSIVE*/
		{MRP_STATE_LA_ACTIVE,{MRP_PA_LA_STARTLEAVEALLTIMER,MRP_PA_LA_MAX}},
	}
};