MRP_FSM_TBL_S g_astMrpFsmTblPeriodic[MRP_EVT_PRD_MAX][MRP_STATE_PRD_MAX] = 
{
	/*MRP_EVT_PRD_BEGIN*/
	{	/*MRP_STATE_PRD_ACTIVE*/
		{MRP_STATE_PRD_ACTIVE,{MRP_PA_PRD_STARTPERIODICTIMER,MRP_PA_PRD_MAX}},
		/*MRP_STATE_PRD_PASSIVE*/
		{MRP_STATE_PRD_ACTIVE,{MRP_PA_PRD_STARTPERIODICTIMER,MRP_PA_PRD_MAX}},	
	},
	/*MRP_EVT_PRD_PERIODICENABLE*/
	{	/*MRP_STATE_PRD_ACTIVE*/
		{MRP_STATE_PRD_MAX,{MRP_PA_PRD_MAX,MRP_PA_PRD_MAX}},
		/*MRP_STATE_PRD_PASSIVE*/
		{MRP_STATE_PRD_ACTIVE,{MRP_PA_PRD_STARTPERIODICTIMER,MRP_PA_PRD_MAX}},
	},
	/*MRP_EVT_PRD_PERIODICDISABLE*/
	{	/*MRP_STATE_PRD_ACTIVE*/
		{MRP_STATE_PRD_PASSIVE,{MRP_PA_PRD_MAX,MRP_PA_PRD_MAX}},
		/*MRP_STATE_PRD_PASSIVE*/
		{MRP_STATE_PRD_MAX,{MRP_PA_PRD_MAX,MRP_PA_PRD_MAX}},
	},
	/*MRP_EVT_PRD_PERIODICTIMER*/
	{	/*MRP_STATE_PRD_ACTIVE*/
		{MRP_STATE_PRD_ACTIVE,{MRP_PA_PRD_STARTPERIODICTIMER,MRP_PA_PRD_PERIODIC}},
		/*MRP_STATE_PRD_PASSIVE*/
		{MRP_STATE_PRD_MAX,{MRP_PA_PRD_MAX,MRP_PA_PRD_MAX}},
	},
};

UINT32 MRP_FSM_PRD_ProcEvt(MRP_FSM_PRD_S* pstFsmPrd, UCHAR ucEvt, MRP_MRPPAT_S* pstParti, VOID* pThis)
{
	
};